name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build with Webpack
        run: npm run build  # Replace with your actual build script if it's different

      - name: copy html
        run: mkdir _site && cp index.html _site/index.html && cp -R dist _site/dist && cp -R images _site/images && cp -R styles _site/styles

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: _site/

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
